### ISSUE TITLE
Large red cannon

### ISSUE THREAD

**Issue by xackery** [loudsmilestudios/TetraForce#154]
similiar to #153

**Comment by xackery** [comment]
![red_cannon](https://user-images.githubusercontent.com/845670/90223873-b566dd00-ddc3-11ea-9fcb-eb5b26c3a91b.png)

**Comment by xackery** [comment]
![red_cannon_fuse](https://user-images.githubusercontent.com/845670/90224448-8b61ea80-ddc4-11ea-9a67-0f02b903997d.png)
with fuse version

**Comment by Nodding** [comment]
This is now in the game.
