### ISSUE TITLE
Constrain Enemies to Boundaries & Camera

### ISSUE THREAD

**Issue by rdg922** [loudsmilestudios/TetraForce#182]
**Related Issues:**
NPCS: #170 
Boundaries & Camera: #181

**Comment by Elginive** [comment]
I also now think this is a non-issue.

**Comment by josephbmanley** [comment]
Right now, in zones NPCs will leave the camera area. This should not happen.

See TetraScript implementation for reference

**Comment by josephbmanley** [comment]
@Elginive I think I'll need some steps to replicate when you have the time.
