### ISSUE TITLE
Able to move while dialogue is active

### ISSUE THREAD

**Issue by rdg922** [loudsmilestudios/TetraForce#199]
Did not attempt to reproduce, got this from @fornclake https://streamable.com/g8otjc

**Comment by rdg922** [comment]
Found the cause. The player dies while in dialogue. Add some checks so this and #200 will be solved together

**Comment by Elginive** [comment]
Not Stale.

**Comment by Elginive** [comment]
Not Stale.

**Comment by Nodding** [comment]
Closed by #304
