### ISSUE TITLE
Saving & Loading Game Data

### ISSUE THREAD

**Issue by josephbmanley** [loudsmilestudios/TetraForce#220]
**Description**

We want a save game button in an ESC menu (See #105)

After main screen (game entry-point) go to loading screen (Stardew style)

**Comment by josephbmanley** [comment]
Okay, so starting some prep-work planning for this... 

What data needs to be saved? Do we just need to save items and certain events?

My current thought is saving:
- Player
    - Inventory (unlock items & ammo count)
    - Current Map
    - Position
- New `global.world_state` dictionary that can be used for building out new features that need to be saved.

**Comment by Elginive** [comment]
There is also dungeon_handler.gd that will require some saving, it keeps track of keys and stuff

**Comment by Nodding** [comment]
First thoughts coming to my head- instead of position should we save the last spawn position? I feel people loading into games with weird positions could introduce some bugs. 

Also would opened chests (ex: power orbs, unlocked weapons) be in that global dictionary?

**Comment by josephbmanley** [comment]
> There is also dungeon_handler.gd that will require some saving, it keeps track of keys and stuff

Okay, what exactly does the `dungeon_handler.gd` do? Is there multiple instances of it? If not, my thought is on a save loaded signal, the dungeon handler could update the keys value.



> First thoughts coming to my head- instead of position should we save the last spawn position? I feel people loading into games with weird positions could introduce some bugs.

Good point, much better idea.

> Also would opened chests (ex: power orbs, unlocked weapons) be in that global dictionary?

They could be implemented in that way if it does not have a check if you already have the item. @Elginive, are you able to confirm that this would have to be saved as well?

**Comment by josephbmanley** [comment]
Okay so `network.states` works as that global dictionary. So that part already exists. so that'll handle 99% of things.

What's left is:
- Save Flow
- Player Specific Data
  - Pos
  - Items
  - Ammo

I think a design discussion might be worthwhile to work through the ideas of implementing these.

**Comment by Elginive** [comment]
@fornclake and I will be working on a system that will create a place for all of the Player Specific Data (see #239) - It may make more sense to make a new issue based on that particular thing, rather than the issue it's currently in relation to. That way there will be more specific information how how we are going to set out what we are doing. it will solve several things, one being the collectable desync bug, as well as collect the information needed for save files.  In the mean time, we can work on the save flow and getting the UI in place, so that way once we have the information for the save files, it's just a matter of plugging it into the UI.

**Comment by josephbmanley** [comment]
@Elginive Could you upload the image of your UI mockup here?

**Comment by josephbmanley** [comment]
Progress update on the UI. Still need to figure out spacing and all of that.
![image](https://user-images.githubusercontent.com/21203171/133519294-32b1741b-617e-4687-8838-c8c7643eedd2.png)
The % is also just a random number to demonstrate we can display save data on this screen as well.

**Comment by Elginive** [comment]
![image](https://user-images.githubusercontent.com/55040983/133535152-091dd7e3-1dce-44ba-b8ec-accd11489259.png)
Here is a more refined concept of what I had in mind.

**Comment by josephbmanley** [comment]
Systems needed added:
- [ ] Loading save file names & metadata
- [ ] Associating saves with lobbies
- [ ] Implement improved GUI

**Comment by josephbmanley** [comment]
UI looking gradually closer:
![image](https://user-images.githubusercontent.com/21203171/133874013-487d3750-baa5-456f-99e9-07e850fbc64a.png)

It obviously still needs a lot of work, but it's a mix of the previous update and the concept image.

**Comment by josephbmanley** [comment]
![image](https://user-images.githubusercontent.com/21203171/134793102-85a2a0f8-f53e-4a77-b0a9-279c19dce927.png)
GUI update
