### ISSUE TITLE
More detailed options screen

### ISSUE THREAD

**Issue by josephbmanley** [loudsmilestudios/TetraForce#222]
**Description**

Major Hitlist for this includes:
- [x] Volume
- [ ] PvP Toggles

**Comment by josephbmanley** [comment]
Okay, so looking through how to do this. After a bit of experimenting, it is looking like options screen might have to be broken down a bit.

So here are my subtasks:
- [ ] Move Character Selection & Keybinds to independent nodes
- [ ] Create tab container for options holding each
- [ ] Have the ability to create an instance of that node from the main menu & the esc menu
- [ ] Add `Sound` tab
- [ ] Add PvP toggle to probably same area as character creation, maybe `Gameplay`?

**Comment by Elginive** [comment]
What about putting the PvP toggle right beside the host button before the server is created? That way, it's very visible and quick to toggle. I'm not sure if you want to be able to toggle between it during gameplay as well, that may have to be part of the ESC menu or something.

**Comment by josephbmanley** [comment]
> What about putting the PvP toggle right beside the host button before the server is created? That way, it's very visible and quick to toggle. I'm not sure if you want to be able to toggle between it during gameplay as well, that may have to be part of the ESC menu or something.

Is that something only configurable on the server?

**Comment by josephbmanley** [comment]
Okay, so for the PvP toggle, my thought is that if it's a server-wide thing (like PvP & PvE servers), we'll have to build out a server config system. (Like a global dictionary of data that is server authoritative that syncs with clients) so that data can be handled.

If it's a player to player thing, we could just add it to the globals and if the incoming damage is detected to be from a player, it will just ignore it.

Pick your poison.

**Comment by Nodding** [comment]
I think server configuration would be great, but how long would that take? If too long we can push that to down the line/with the rewrite.
