### ISSUE TITLE
ENEMY: Turtle

### ISSUE THREAD

**Issue by Elginive** [loudsmilestudios/TetraForce#231]
**Description**

Enemy Visual: (Concept Art)

Enemy Behavior: LA Octorok behavior.

**Comment by Nodding** [comment]
May end up doing this early, possibly Milestone 2... idea I had was to have the animation that plays while a player is close be the turtle in its shell with bulging eyes looking left and right in a somewhat comedic fashion. 

It can flip between just 2 sprites for three total frames needed, one looking to the side, then the middle, then the side sprite merely flipped over.
