### ISSUE TITLE
Ammo desync issues on multiplayer

### ISSUE THREAD

**Issue by Nodding** [loudsmilestudios/TetraForce#239]
![image](https://user-images.githubusercontent.com/32770553/119408468-c417e400-bcb3-11eb-871d-34d322a4107b.png)

Pasted error for copy/paste-ability: SCRIPT ERROR: _on_collect: Invalid call. Nonexistent function 'update_weapons' in base 'Nil'.
          At: res://entities/collectables/arrow.gdc:5
**OS:**

Windows 10

**Issue description:**

Ammo does not seem to spawn the same for each player. When a player picks up an item they can't see, but another can, the error above appears.

**Steps to reproduce:**

Have at least 2 players connect to a server.
Player 2 cuts grass until Player 1 sees an item.
When Player 2 picks the item up, Player 1 receives the error.

**Comment by Nodding** [comment]
Will fix this, unsure exactly what causes this. Happens in 3.2.3 and 3.3.2.

**Comment by Nodding** [comment]
Interesting discovery: even if the item spawns for both players, this error still appears.

**Comment by Elginive** [comment]
All is fixed except for when entering a room.

**Comment by Elginive** [comment]
I made a comment on a different issue, but this is the issue I meant @fornclake and I will tackle by a backport feature in TetraScript.
