### ISSUE TITLE
Tilemap does not update on entering a zone

### ISSUE THREAD

**Issue by josephbmanley** [loudsmilestudios/TetraForce#248]
![image](https://user-images.githubusercontent.com/21203171/120055169-4c72ed80-c002-11eb-8f0f-b48c63c3d0ca.png)

**Issue description:**

The grass auto-tile will not update when entering a new room.

**Steps to reproduce:**

Player 1 enters room and cuts grass
Player 2 enters room after grass has been cut
Player 2 will have messed up tilemap

**Comment by Nodding** [comment]
To be fixed, then reworked (collectibles)

**Comment by Elginive** [comment]
@fornclake and I will tackle this, we are going to backport a TetraScript system to handle this and some other things.

**Comment by Elginive** [comment]
This has been fixed during my networking adventures.
