### ISSUE TITLE
Translation system

### ISSUE THREAD

**Issue by LucasSnatiago** [loudsmilestudios/TetraForce#266]
**Description**

Why not using [Godot's language system](https://docs.godotengine.org/en/stable/tutorials/i18n/internationalizing_games.html) to make this game more international. I can help translation for brazilian portuguese, for example.

**Comment by josephbmanley** [comment]
This seems like a pretty nice idea I'd love to see implemented.

Would you be interested with us on working on an implementation? I would think our English stuff would have to move there as well, correct?

**Comment by LucasSnatiago** [comment]
Yes, I'd love to, and yes man, some stuff needs to change, but it's very easy.

A simple csv file, for example could hold all the strings.
