### ISSUE TITLE
PvP Toggle

### ISSUE THREAD

**Issue by josephbmanley** [loudsmilestudios/TetraForce#277]
Servers should be configurable as either PvP or PvE

Continued from #222

**Comment by Elginive** [comment]
PR 304 gets the functionality for this working- there is a Boolean Variable called "pvp" in global.gd that needs to be connected to the misc options button (which I've created) and then retain / save that like the other options.  I believe once that has been done this issue will be completed.

**Comment by Nodding** [comment]
Closed by #304
