### ISSUE TITLE
MacOSX: Null instance error

### ISSUE THREAD

**Issue by Epiculy** [loudsmilestudios/TetraForce#289]
**OS:**
MacOSX

No server

**Issue description:**
Get this error when trying to load singleplayer: Attempt to call functaion'instance' in base 'null instance' on a null instance on line 103 in main.gd ( var level = load(default_map).instance() )

**Steps to reproduce:**
Press the run arrow and click singleplayer?

**Comment by josephbmanley** [comment]
Hi @Epiculy!

Thanks for the bug report!

We'll look into this. It seems to be an error specific to the Mac build as I was not able to replicate it on Linux.

**Comment by Nodding** [comment]
@Epiculy Thank you for bringing this to our attention. Could you be more specific as to what build of Mac OS you are using?

**Comment by Nodding** [comment]
Tested on Catalina, runs fine.

**Comment by Epiculy** [comment]
> Tested on Catalina, runs fine.

I am on MacOS High Sierra version 10.13.6 running Godot v3.2.3 Stable release

**Comment by Nodding** [comment]
The game currently is made to be running on Godot 3.3.2, are you able to install that? 

We also have builds of the game to download from our website and github directly (if you go to actions and scroll down.)

**Comment by Nodding** [comment]
Closing to do age and because user was not running on Godot version game is made in, I assume this is what caused the error.
