### ISSUE TITLE
Clarification on License Usage

### ISSUE THREAD

**Issue by 8bitKyle** [loudsmilestudios/TetraForce#303]
Hello, I'm new to developing using the Godot game engine and I just came across your project and see that you also have a MIT license on it permitting commercial use. I couldn't find a contact email, so hopefully I can ask here.

What I wanted to ask for clarification on is that I have a game created in a different game engine that I want to finish developing in Godot and this project is almost exactly like the game I was working on. So, I wanted to ask if I can use the code base to re create the game I was working on and be able to sell it?

The differences in my game is that the multiplayer won't be online, just local. My game's art style is more towards the SNES and will not be an "asset flip". I just wanted to ask for clarification, since this project looks like it took a lot of effort to make.

**Comment by Elginive** [comment]
Hi Kyle, thank you for reaching out to us and asking for clarification / permission. That's very respectable of you :)
The short answer is yes, you may utilize our engine for your own purposes- and I appreciate the clarity on your intent. We have made this version of the engine available for others to learn and pull from. I am happy to hear that this sounds useful to you, I would love to learn more about your project and see what you've done so far. Also feel free to join our discord and if you have any questions, feel free to reach out to me. I will do my best to help.

**Comment by Elginive** [comment]
If you have any further questions reach out to us again :)
