### ISSUE TITLE
Discord invite in readme (and on tetraforce.io) is invalid

### ISSUE THREAD

**Issue by Polatrite** [loudsmilestudios/TetraForce#305]
The current Discord links (https://discord.gg/cxTBVCZ) on:

* This repo's readme
* Tetraforce.io
* Tetraforce twitter account

are all currently invalid.

**Comment by Elginive** [comment]
Thank you for letting us know, I've fixed the website and will get the other ones fixes asap.

**Comment by Elginive** [comment]
Twitter still needs to be updated, but the main sources are fixed.
