### ISSUE TITLE
Cannon Blocked

### ISSUE THREAD

**Issue by josephbmanley** [loudsmilestudios/TetraForce#312]
**Issue description:**

Cannon only fires once, so if it is blocked you can get soft locked.

**Steps to reproduce:**

Go to part of the game with statues blocking cannon and fire cannon with statue in front of cannon.

**Comment by Nodding** [comment]
I think initially we wanted to have the cannon fire only once but honestly I'd agree it'd be nice to be able to fire it over and over even if it isn't "realistic."

**Comment by Elginive** [comment]
I agree. I made it like that on purpose. But it can cause issues, so it's just better to have it endless for now.
