### ISSUE TITLE
Can't push barrels in pirate ship

### ISSUE THREAD

**Issue by octo7777** [loudsmilestudios/TetraForce#320]
![Screenshot (42)](https://user-images.githubusercontent.com/91641487/135365703-09c428c7-dc55-4e6c-8f9b-60d5b14ea214.png)
![Screenshot (43)](https://user-images.githubusercontent.com/91641487/135365848-c7aea0f8-a674-4d18-b870-2b4ab28cc39f.png)

I was playing multiplayer with my friend, and we couldn't figure out how to solve this puzzle. At first we though we were missing some kind of hookshot item, but we couldn't find anything on the rest of the map. Looking at the other bug reports it seems we are supposed to push these barrels. We can't figure out how though. Arrows get stopped by the water and we can't fall in. The wheel that resets puzzles in that other room does nothing here either. Did we break something? My friend brought a statue here too in the second screenshot and we can't push that in either but that might be intentional.

Also, when we left the ship to look for more items, the puzzles reset and the vines blocking the boss door came back. But when we went to the red boss cannons, we can't reactivate them.

I'm not sure how we got this to happen. The cannons resetting is probably from leaving the dungeon and coming back

Hope this helps! The game was really fun so far!

**Comment by octo7777** [comment]
I tried going into single player, and I still can't push the barrel, but the red cannons reset

**Comment by josephbmanley** [comment]
Hi @octo7777, thanks for the bug report!

So the barrels should be able to be pushed into the water, but only when built from source. The current release (v0.2.0/v0.3.0) does not include the fully implemented barrels, but that code implementation was just merged in so if you build from source or wait for v0.4.0 to be released (probably sometime this week), the barrel puzzle should work.

Also the final boss is currently not in the game right now, so the vines are only partially implemented. When #125 is feature complete, the red cannon & vines should be fixed. :smile: 

If you have issues with the code in mainline or have additional feedback on the following feel free to reopen this issue!

**Comment by octo7777** [comment]
Ohhh I see, thank you so much!!
