### ISSUE TITLE
Invulnerability not working as originally coded

### ISSUE THREAD

**Issue by Elginive** [loudsmilestudios/TetraForce#338]
**Game Version:**

Master Branch

**Issue description:**

Invulnerability should occur after player is injured, giving 60 ticks of no damage, this however does not occur. This feature should also be usable with enemy logic / behaviors- which that does not seem to be the case.

Possibly broken during PvP meddling. This could be a good place to start, but at this moment, unsure.

**Steps to reproduce:**

Walk into an enemy consecutive times while still flashing.

**Comment by josephbmanley** [comment]
This can be fixed by having the player connect to the options loaded function.

Then update a value on the player and make a peer call to update that value on all machines.

Finally, the entity `damage` function should use that variable when determine whether the player will process that damage.

**Comment by josephbmanley** [comment]
Within the recent changes by @Elginive, it now requires the full implementation of the player PvP Toggle again
