### ISSUE TITLE
Shooting Sleeping Enemy

### ISSUE THREAD

**Issue by MichaPika** [loudsmilestudios/TetraForce#341]
**OS:**
Windows

**Game Version:**
v0.4.0

**Issue description:**
Shooting Enemy's while they're sleeping causes them to flash, and not "die" until you get near them

**Steps to reproduce:**
Shoot an arrow from a distance at a sleeping enemy

![GameScreenshot](https://user-images.githubusercontent.com/72245562/141841816-70fde06d-deb1-4219-b827-7baffd809518.png)

**Comment by Nodding** [comment]
Hi, thank you for the bug report! This issue was discovered recently and fixed within the enemy turtle PR #342. Once it is merged, this should be resolved.

**Comment by Nodding** [comment]
Resolved by #342
