### ISSUE TITLE
"Defeat all enemies" door

### ISSUE THREAD

**Issue by fornclake** [loudsmilestudios/TetraForce#7]
Need a door the closes when the player is fully inside the room and there are active enemies, and then unlocks when all enemies are defeated.

Note that entity_detect can be used to get the amount of enemies on screen, as that controls enemy processing.

**Comment by Dobbelsteen** [comment]
In theory, this is fairly easy to do.

However, taking networking, and other players into account, using the entity_detect method to count the enemies might give incorrect values.
For example if 2 players are in different "zones" of a particular map, the enemies of both of these zones would get counted towards to the total in the current implementation.

So we would need something along the lines of entity_detect_for_player_in_this_particular_room, if you catch my drift.

Maybe something nicer and more generic would be to have an is_room_cleared signal of some sort, that can be linked to a door.

Or maybe there's a very simple solution I'm not seeing right now

Networking makes life a lot harder 😅

**Comment by IQGobo** [comment]
Maybe the concept still applies if we add a special group for each such puzzle room instead of using one global "entity_detect" group?

That group could detect the presence of "kill all" doors and enemies as well as stop processing early when no player is nearby.

**Comment by marcJV** [comment]
Currently have a room object in tiled, we can add a clear state to it with keys like, "none", "defeat-all", "light-torches" or something shorter if needed. Then in code each room can have a status and a clear condition attached to it

**Comment by IQGobo** [comment]
Maybe "defeat all enemies" type rooms require a visible trigger in the room, so that players can chose to wait for other players to arrive until they activate the trap. Would not hurt single player at all. A special floor tile graphic would be enough to hint about this.

**Comment by josephbmanley** [comment]
![image](https://user-images.githubusercontent.com/21203171/119212950-c565c880-ba89-11eb-885d-28ea51636337.png)
